### ISSUE TITLE
Update to salmon equivalence class output

### ISSUE THREAD

**Issue by rob-p** [Oshlack/ec-dtu-pipe#1]
Hi all,

  Hope you are all well! I’m just writing to let you know that, starting in salmon 1.2.0 (which was just released), the equivalence class output is gzipped by default.  This is something which should be easy to take clear of in your processing scripts (the format of the file remains identical to previous versions, its just that the text format file itself is now gzipped).  You should be able to simply check the file extension (or salmon version), and wrap the equivalence class reader in a gzip reader / stream.  This nicely compresses the size of the equivalence class files, which is particularly useful now that we also [have a downstream tool that relies on them in the output across multiple samples](https://github.com/COMBINE-lab/terminus).

—Rob

**Comment by mcmero** [comment]
Hi Rob,

Thanks for the heads up! We also have another tool that is reliant on the EC output format, so I will make sure to implement this going forward.

Cheers,
Marek

**Comment by mcmero** [comment]
Support for the new file format changes have now been implemented.
